version: "3.3"

services:
  educai:
    image: mongo:4.4.6
    container_name: educai
    ports:
      - "27017:27017"
  backend:
    image: openjdk:17
    container_name: backend
    command: java -jar home/java-app
    volumes:
      - ./java-app/target/educai-0.0.1-SNAPSHOT.jar:/home/java-app
    depends_on:
      - educai
    ports:
      - "8080:8080"
  frontend:
    image: node:18-alpine
    command: tail -f /dev/null
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"