version: '3.3'

networks:
  educai-network:

services:
  educai:
    image: mongo:4.4.6
    container_name: educai
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: educaiAdmin 
      MONGO_INITDB_ROOT_PASSWORD: i9lnkPC9U46sOg0
    networks:
      - educai-network
  
  backend1:
    image: openjdk:17
    container_name: backend1
    command: java -jar /home/java-app --server.port=8080
    ports:
      - "8080:8080"
    volumes:
      - ./java-app/target/educai-0.0.1-SNAPSHOT.jar:/home/java-app
    depends_on:
      - educai
    networks:
      - educai-network

  backend2:
    image: openjdk:17
    container_name: backend2
    command: java -jar /home/java-app --server.port=8081
    ports:
      - "8081:8081"
    volumes:
      - ./java-app/target/educai-0.0.1-SNAPSHOT.jar:/home/java-app
    depends_on:
      - educai
    networks:
      - educai-network

  backend3:
    image: openjdk:17
    container_name: backend3
    command: java -jar /home/java-app --server.port=8082
    ports:
      - "8082:8082"
    volumes:
      - ./java-app/target/educai-0.0.1-SNAPSHOT.jar:/home/java-app
    depends_on:
      - educai
    networks:
      - educai-network
  
   ia-api:
    image: node:18-slim
    container_name: ia-api
    command: sh -c "apt-get update && apt-get install -y chromium libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libgtk-3-0 fonts-liberation libgbm-dev libxshmfence1 && npm install && node /home/dist/app.js"
    working_dir: /home
    volumes:
      - ./ia-api:/home
    ports:
      - "3000:3000"
    networks:
      - educai-network
